@startuml

package "Site" <<Database>> {
    
}
package "Proveedores" <<Database>> {
    entity "Proveedor" as proveedor {
        * id : Uuid <<PK>>
        --
        * userId : Uuid <<FK>>
        * categoria : INT <<FK>>
        ..
        * nombreLegal : VARCHAR(100)
        * nombreComercial : VARCHAR(100)
        * rfc : VARCHAR(13)
        * descripcion : VARCHAR(500)
        * rating : VARCHAR(4)
        * direccion : VARCHAR(200)
        * ciudad : INT
        * estado : INT
        * pais : INT
    }

    entity "Sucursal" as sucursal {
        * id : Uuid <<PK>>
        --
        * userId : Uuid <<FK>>
        * proveedorId : Uuid <<FK>>
        ..
        * nombre : VARCHAR(100)
        * direccion : VARCHAR(200)
        * numeroInterior : Int
        * numeroExterior : Int
        * codigoPostal : VARCHAR(10)
        * ciudad : INT
        * estado : INT
        * pais : INT
    }

    entity "Servicio" as servicio {
        * id : Uuid <<PK>>
        --
        * proveedorId : Uuid <<FK>>
        ..
        * name : VARCHAR(100)
        * duration : INT
        * descripcion : VARCHAR(500)
        * precio : Float
    }

    entity "CategoriasProveedores" as categoria {
        * id : Int <<PK>>
        --
        * nombre : VARCHAR(100)
        * descripcion : VARCHAR(500)
        * iconUrl : VARCHAR(200)
        * EsProfesionista : BOOLEAN
    }

    entity "CategoriasServicios" as categoria {
        * id : Int <<PK>>
        --
        * nombre : VARCHAR(100)
        * descripcion : VARCHAR(500)
        * iconUrl : VARCHAR(200)
    }

    entity "Horario" as horario {
        * id : Uuid <<PK>>
        --
        * proveedorId : Uuid <<FK>>
        ..
        * diaSemana : Int
        * horaApertura : VARCHAR(20)
        * horaCierre : VARCHAR(20)
        * horaInicio : VARCHAR(20)
    }

    entity "Documentacion" as documentacion{
        * id : Uuid <<PK>>
        --
        * proveedorId : Uuid <<FK>>
        * category : Int <<FK>>
        ..
        * tipo : VARCHAR(100)
    }

}
package "Usuarios" <<Database>> {
    entity "Usuario" as usuario {
    * id : Uuid <<PK>>
    --
    * nombre : VARCHAR(100)
    * apellido : VARCHAR(100)
    * acercaDeMi : VARCHAR(500)
    * correo : VARCHAR(100)
    * contraseña : VARCHAR(100)
    * telefono : VARCHAR(20)
    * telefonoWhatsapp : VARCHAR(20)
    * fechaNacimiento : Date
    * sexo : VARCHAR(1)
    * profilePhotoUrl : VARCHAR(200)
    }

}

package "Citas" <<Database>> {

    entity "Citas" as cita {
        * id : Uuid <<PK>>
        --
        * usuarioId : Uuid <<FK>>
        * proveedorId : Uuid <<FK>>
        * servicioId : Uuid <<FK>>
        ..
        * fechaTentativa : Date
        * horaTentativa : Time
        * status : Int
    }


    entity "StatusCatalogo" as statusCatalogo{
        * id : Uuid <<PK>>
        --
        * text : VARCHAR(100)
    }
}

@enduml